---
title: Director State Diagram
---
stateDiagram-v2
  direction LR

  s1:GetMap
  state s2 <<choice>>
  s3:Explore
  s4:Patrol
  state s5 <<choice>>
  s6:Return to Base



  [*] --> s1
  s1 --> s2:Is enviroment full mapped ?
  s2 --> s3:No
  s3 --> s1
  s2 --> s4:Yes
  s4 --> s5:Intruder detected ?
  s5 --> s4:No
  s5 --> s6:Yes
  s6 --> [*]
