---
title: Behaviour State Diagram
---
stateDiagram-v2
  direction LR
  state Update {
    direction LR
    [*] --> s1
    s1 --> s2
    s2 --> [*]
  }
  state Plan {
    direction LR
    [*] --> d1
    state choice1 <<choice>>

    d1 --> choice1:Is environment fully mapped?
    choice1 --> d3:No
    d3 --> d7
    choice1 --> d4:Yes
    state choice2 <<choice>>

    d4 --> choice2:Intruder detected?
    choice2 --> d8:No
    choice2 --> d6:Yes
    d6 --> d7
    d8 --> d7
    d7 --> [*]
  }
  state Act {
    direction LR
    [*] --> c1
    state choiceA <<choice>>

    c1 --> choiceA:Is queue empty?
    choiceA --> c2:No
    choiceA --> c3:Yes
    state choiceB <<choice>>

    c2 --> choiceB:Successful?
    choiceB --> c1:Yes
    choiceB --> c3:No
    c3 --> [*]
  }
  [*] --> Initialize
  Initialize --> Update
  Update --> Plan
  Plan --> Act
  Act --> Update
  Update:Map
  s1:Read sensors
  s2:Updates near map positions
  Plan:Director
  d1:GetMap state
  d3:Explore
  d4:Patrol state
  d6:Return to Base
  d7:Save actions planned
  d8:Keep patrolling
  Act:Controller
  c1:DeQueueAction
  c2:ExecuteAction
  c3:SaveExitStatus
