---
title: Behaviour State Diagram
---
stateDiagram-v2
  direction LR

  [*] --> Initialize

  state "Initialize" as Initialize
  state "Update Map" as Update
  state "PlanActions" as Plan
  state "Act" as Act

  Initialize --> Update
  Update --> Plan
  Plan --> Act
  Act --> Update : ActionQueue empty
  Plan --> [*]
